# Generated by Django 4.2.5 on 2023-09-12 12:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unique_id',
            field=models.CharField(default='None', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(limit_choices_to={'chats__participants__count': 2}, related_name='chats', to=settings.AUTH_USER_MODEL),
        ),
    ]
