# Generated by Django 4.2.5 on 2023-09-12 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_chat_unique_id_alter_chat_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
