# Generated by Django 4.2.5 on 2023-09-12 13:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0003_alter_chat_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
