# Generated by Django 4.2.5 on 2023-09-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_alter_chat_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='unique_id',
            field=models.UUIDField(default=None, null=True, unique=True),
        ),
    ]
